version: '3'

services:
    db:
        image: 'postgres:13.1-alpine'
        container_name: smart-home-db
        environment:
        - POSTGRES_DB=smart-home-db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123456
        # - ALLOW_IP_RANGE-0.0.0.0/0
        ports:
        - "5432:5432"
    backend:
        image: 'smart-home:latest'
        build:
            context: backend
        container_name: smart-home-backend
        ports:
        - "8080:8080"
    